### PR TITLE
Fix broken event system

### PR DESCRIPTION
**Pull request by roelvanduijnhoven**
See comment below.

### CODE REVIEW

**Comment by roelvanduijnhoven** [comment]
This PR tries to make the (shared) event system functional again under ZF3. See #678. It addresses all these points by:

* Make sure to tag all classes using the EventManager with `EventManagerAwareInterface`.
* Make sure that we do not set a shared manager ourselves; otherwise ZF3 will not properly inject its own version.
* Set the `EventManager` directly ourselves on the `AdapterChain` method such that events set in the factory are not lost.
* Send a custom `AdapterChainEvent` to listeners of `AdapterChain`. This is in line with how it was under ZF2 and does not require hacks.

With these fixes our app functions the way it did before. The only change was to replace the `init` events with a delegator for those forms.

The tests *do* need to be updated. But wanted to get some feedback first about if this will be merged. 
@Danielss89 What do you think about this?

**Comment by roelvanduijnhoven** [comment]
Would love to hear some feedback @Danielss89, maybe @netiul? Now working of a patched version myself; but not ideal!

**Review by bartmcleod — APPROVED** [review]

**Review by APaikens — APPROVED** [review]
Tested locally, these changes work - and it helps a lot.

**Comment by Danielss89** [comment]
Looks good to me. Haven't tested this yet though.

**Comment by olexp** [comment]
This can be removed from adapters and AdapterChain:
use Zend\EventManager\EventInterface;

These changes work for me. @Danielss89 could you merge the request?

**Review by asgrim — APPROVED** [review]

**Comment by asgrim** [comment]
@Danielss89 poke on this? :)

**Comment by asgrim** [comment]
Thanks! :+1:

**Comment by roelvanduijnhoven** [comment]
Thanks @Danielss89 a bunch: much appreciated. Now I can stop with working based of strange forks and branches. Could you perhaps release a new version?

**Comment by zluiten** [comment]
What about releasing a new version @Danielss89 ?

**Pull request merged**
