### PR TITLE
Remove minimum username length restriction

### LINKED ISSUE #553: Arbitrary user name length restriction
Register form has a length filter which rejects anything < 3 or > 255.  This should be configurable instead of hard-coded.  

https://github.com/ZF-Commons/ZfcUser/blob/master/src/ZfcUser/Form/RegisterFilter.php#L40

### PR DESCRIPTION
**Pull request by adamlundrigan**
Closes #553

### CODE REVIEW

**Comment by adamlundrigan** [comment]
oops

**Comment by stijnhau** [comment]
Can't this be merged in?

**Comment by stijnhau** [comment]
??

**Comment by Danielss89** [comment]
Yes i guess it can.

**Pull request merged**
