### PR TITLE
do not allow 5.6 failures and add php7 to test matrix

### PR DESCRIPTION
**Pull request by svycka**

### CODE REVIEW

**Comment by texdc** [comment]
I'd allow `5.4` and `5.5` to fail.

**Comment by svycka** [comment]
Why? If this those versions are supported?

**Comment by texdc** [comment]
They're EOL.

**Comment by stijnhau** [comment]
Oke that they are EOL.
But this is a existing versions that only will be updated.

Could you also create a PR with same change for the master branch?

**Comment by stijnhau** [comment]
Can this be merged?
And can the same PR be created for the master branch?

**Comment by stijnhau** [comment]
@Danielss89 
Is that the correct label?
1.4.1 is already released even an 1.4.2
I think this should have the label 1.5.0

**Comment by Danielss89** [comment]
Whoops. Changed tag to 1.4.3

**Comment by stijnhau** [comment]
Indead 143 is even better 
150 can be for racatored servicelocater thingie

**Pull request merged**
