### PR TITLE
Add the ability to view a user's profile details

### PR DESCRIPTION
**Pull request by settermjd**
I need the ability, in an application which I'm creating, which uses ZfcUser, to allow a user to view their profile details. So I created this pull request to add the functionality to the library. I'm not 100% knowledgeable about the library, but have attempted to implement it following the existing style. I'm keen to add in functionality to allow a user to modify their profile as well.

### CODE REVIEW

**Comment by Danielss89** [comment]
Thank you for using ZfcUser, and for taking the time to do a Pull Request.
The goal with ZfcUser 2.0(master) is to keep it as simple as possible, with as few features as possible. All extra features will then be done in extra modules.
A user profile page is often very custom, so i wouldn't add that to a module either, that should be up to the developer to do himself :)

**Comment by stijnhau** [comment]
Indead agreeing with @Danielss89.
Make a separate module of it.
Lot of option to show email or not and so on.

**Comment by ojhaujjwal** [comment]
I agree with @Danielss89 too! A user profile page is often very custom,

**Comment by settermjd** [comment]
Fair enough. Thanks for the clarification.

**Pull request closed without merging**
